### ISSUE TITLE
Dados de Setores e Data do Último Balanço

### ISSUE THREAD

**Issue by michelmetran** [alexcamargos/pyFundamentus#4]
Inicialmente parabéns pelo desenvolvimento.
Estive usando e gostei. Substituiu outro pacote que eu utilizava.

Gostaria de sugerir que no processo de scrapy também fosse obtido os dados dessa "seção" no HTML,

https://fundamentus.com.br/detalhes.php?papel=WEGE3&interface=mobile

![](https://i.imgur.com/V4Udr8W.png)

 tais como
- Valor de mercado
- Valor da firma
- Nº de ações
- Último balanço
- Setor
- Subsetor

**Comment by alexcamargos** [comment]
Olá!

Agradeço muito pelos elogios e pelo feedback!

Fico muito contente em saber que o módulo que desenvolvi está sendo útil para você e que substituiu com sucesso outra solução que você utilizava.

A sua sugestão foi implementada! Agora, o processo de scrapy também captura os dados daquela seção específica no HTML, incluindo (Valor de mercado, Valor da firma, Nº de ações, Último balanço, Setor, Subsetor).
![wege3](https://github.com/user-attachments/assets/81b96c00-2715-410c-9376-d0741f2d6e35)

Gostaria de pedir que você faça alguns testes com essa nova funcionalidade e me forneça um retorno sobre o que achou. Seu feedback é extremamente valioso para que eu possa continuar aprimorando o módulo.

Mais uma vez, muito obrigado por usar o meu módulo! Estou aqui para ajudar e sempre aberto a novas sugestões.

Um abraço!
